name: 'Joyfully Awake!'
favicon: null
layout_spectrum: 0.48316494771279395
typography_spectrum: 0.8264778994489461
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.34986184956505895
  lightness: 0.10373694682493806
  saturation: 0.5421128927264363
  rhythmicContrast: 0.8039391108322889
purpose: []
